"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { format } from "date-fns";
import { CalendarIcon, Search, Download, Filter } from "lucide-react";
import LoaderAnim from "@/components/LoaderAnim";
import apiClient from "@/lib/api";

const UsageHistory = () => {
  const [usageData, setUsageData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("all");
  const [dateRange, setDateRange] = useState({ from: null, to: null });
  const [totalCoins, setTotalCoins] = useState(0);
  const [usageStats, setUsageStats] = useState({
    selfModel: 0,
    poster: 0,
    youtube: 0,
    copywriting: 0,
  });

  // Fetch real usage history data from API
  useEffect(() => {
    const fetchUsageHistory = async () => {
      try {
        setLoading(true);
        const response = await apiClient.usageHistory.getUsageHistory();

        // Process the API response
        const historyData = response.data || [];

        setUsageData(historyData);

        // Calculate total credits and usage statistics
        const total = historyData.reduce(
          (sum, item) => sum + (item.credits || 0),
          0
        );
        setTotalCoins(total);

        const stats = {
          selfModel: historyData
            .filter((item) => item.type === "self_model")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          poster: historyData
            .filter((item) => item.type === "poster")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          youtube: historyData
            .filter((item) => item.type === "youtube")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          copywriting: historyData
            .filter((item) => ["caption", "blog_headings"].includes(item.type))
            .reduce((sum, item) => sum + (item.credits || 0), 0),
        };
        setUsageStats(stats);
      } catch (error) {
        console.error("Error fetching usage history:", error);
        // Handle error state if needed
      } finally {
        setLoading(false);
      }
    };

    fetchUsageHistory();
  }, []);

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
  };

  const handleFilterChange = (value) => {
    setFilterType(value);
  };

  const handleDateSelect = (range) => {
    setDateRange(range);
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return format(date, "MMM d, yyyy");
  };

  const exportCSV = () => {
    const headers = [
      "Type",
      "Content",
      "Credits",
      "Date",
      "Generated By",
      "Status",
    ];
    const csvData = filteredData.map((item) => [
      item.type,
      item.content?.text || "",
      item.credits || 0,
      formatDate(item.createdAt),
      item.generatedBy || "",
      item.status,
    ]);

    const csvContent = [
      headers.join(","),
      ...csvData.map((row) => row.join(",")),
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", "usage_history.csv");
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Filter data based on search term, content type, and date range
  const filteredData = usageData.filter((item) => {
    const contentText = item.content?.text || "";
    const generatedBy = item.generatedBy || "";
    const type = item.type || "";

    const matchesSearch =
      contentText.toLowerCase().includes(searchTerm.toLowerCase()) ||
      generatedBy.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      type.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesType =
      filterType === "all" ||
      type.toLowerCase().includes(filterType.toLowerCase());

    const itemDate = new Date(item.createdAt);
    const matchesDateRange =
      (!dateRange.from || itemDate >= dateRange.from) &&
      (!dateRange.to || itemDate <= dateRange.to);

    return matchesSearch && matchesType && matchesDateRange;
  });

  return (
    <div className="space-y-6 max-w-7xl mx-auto px-4">
      {/* Usage Statistics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Total Coins Used</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{totalCoins}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Self Model</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.selfModel}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.selfModel / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Poster Design</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.poster}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.poster / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">YouTube</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.youtube}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.youtube / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Copywriting</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.copywriting}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.copywriting / totalCoins) * 100)}% of
              total
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Search and Filter */}
      <div className="flex flex-col sm:flex-row gap-4">
        <div className="relative flex-grow">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
          <Input
            placeholder="Search by content, user or type..."
            value={searchTerm}
            onChange={handleSearch}
            className="pl-10"
          />
        </div>
        <div className="flex gap-2">
          <Select value={filterType} onValueChange={handleFilterChange}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Filter by type" />
            </SelectTrigger>
            <SelectContent className="bg-white">
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value="self_model">Self Model</SelectItem>
              <SelectItem value="poster">Poster Design</SelectItem>
              <SelectItem value="youtube">YouTube</SelectItem>
              <SelectItem value="caption">Caption</SelectItem>
              <SelectItem value="blog_headings">Blog Headings</SelectItem>
            </SelectContent>
          </Select>

          <div className="relative">
            <Button
              variant="outline"
              className="w-[240px] justify-start text-left font-normal"
              onClick={() =>
                alert(
                  "Date picker functionality removed - component not available"
                )
              }
            >
              <CalendarIcon className="mr-2 h-4 w-4" />
              <span>Pick a date range</span>
            </Button>
          </div>

          <Button variant="outline" onClick={exportCSV}>
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>
        </div>
      </div>

      {/* Usage History Table */}
      {loading ? (
        <div className="flex justify-center items-center h-64">
          <LoaderAnim />
        </div>
      ) : filteredData.length > 0 ? (
        <Card>
          <CardContent className="p-4">
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-3 px-4">Type</th>
                    <th className="text-left py-3 px-4 hidden md:table-cell">
                      Content
                    </th>
                    <th className="text-left py-3 px-4">Credits</th>
                    <th className="text-left py-3 px-4">Date</th>
                    <th className="text-left py-3 px-4">Generated By</th>
                    <th className="text-right py-3 px-4">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredData.map((item) => (
                    <tr key={item._id} className="border-b">
                      <td className="py-3 px-4">
                        <span
                          className={`inline-block text-center capitalize px-2 py-1 rounded-full text-xs ${getTaskTypeClass(
                            item.type
                          )}`}
                        >
                          {item.type.split("_").join(" ")}
                        </span>
                      </td>
                      <td className="py-3 px-4 hidden md:table-cell max-w-[300px] truncate">
                        {item.content?.text || ""}{" "}
                        {item.content.image ? (
                          <img src={item.content.image} className="max-w-14"/>
                        ) : (
                          ""
                        )}
                      </td>
                      <td className="py-3 px-4 font-medium">
                        {item.credits || 0}
                      </td>
                      <td className="py-3 px-4">
                        {formatDate(item.createdAt)}
                      </td>
                      <td className="py-3 px-4">
                        {item.generatedBy.fullName || ""}
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span
                          className={`inline-block px-2 py-1 rounded-full text-xs capitalize ${
                            item.status === "completed"
                              ? "bg-green-700"
                              : "bg-red-700"
                          }`}
                        >
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      ) : (
        <div className="text-center py-12">
          <Filter className="h-16 w-16 text-gray-400 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">
            No usage history found
          </h3>
          <p className="text-white/70">
            {searchTerm ||
            filterType !== "all" ||
            dateRange.from ||
            dateRange.to
              ? "Try adjusting your search or filters"
              : "No usage history available yet."}
          </p>
        </div>
      )}
    </div>
  );
};

// Helper function for task type styling
const getTaskTypeClass = (type) => {
  switch (type) {
    case "self_model":
      return "bg-blue-100 text-blue-800";
    case "poster":
      return "bg-purple-100 text-purple-800";
    case "youtube":
      return "bg-red-100 text-red-800";
    case "caption":
      return "bg-green-100 text-green-800";
    case "blog_headings":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

export default UsageHistory;
