"use client";

import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { format } from "date-fns";
import { CalendarIcon, Search, Download, Filter } from "lucide-react";
import apiClient from "@/lib/api";
import LineLoading from "@/components/LineLoading";
import Link from "next/link";
// const redirectUrlWithType = (type) => {
//   if(type === "caption" || type === "") {}
//   return `/${type}?${item._id}`;
// };
const UsageHistory = () => {
  const [usageData, setUsageData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("all");
  const [dateRange, setDateRange] = useState({ from: null, to: null });
  const [totalCoins, setTotalCoins] = useState(0);
  const [usageStats, setUsageStats] = useState({
    selfModel: 0,
    poster: 0,
    youtube: 0,
    copywriting: 0,
  });
  const [pagination, setPagination] = useState({
    currentPage: 1,
    totalPages: 1,
    limit: 25,
    totalItems: 0,
  });

  const selectOptions = [
    { value: "all", label: "All Types" },
    { value: "poster_design", label: "Poster Design" },
    { value: "poster_caption", label: "Poster Caption" },
    { value: "intelligent_posters", label: "Intelligent Poster" },
    { value: "virtual_try-on", label: "Virtual Try-On" },
    { value: "script_writer", label: "Youtube Script" },
    { value: "thumbnail_generator", label: "Thumbnails" },
    { value: "caption", label: "Caption" },
    { value: "blog_headings", label: "Blog Headings" },
    { value: "blog", label: "Blog" },
    { value: "keyword_hashtag", label: "Keyword & Hashtag" },
    { value: "product_des", label: "Product Description" },
  ];

  // Fetch real usage history data from API
  useEffect(() => {
    const fetchUsageHistory = async () => {
      try {
        const response = await apiClient.usageHistory.getUsageHistory(
          pagination.currentPage,
          pagination.limit,
          filterType
        );
        console.log(response);

        // Process the API response
        const historyData = response.data || [];

        // Update pagination information
        setPagination({
          ...pagination,
          totalPages: response.pagination?.totalPages || 1,
          totalItems: response.pagination?.totalCount || 0,
        });

        setUsageData(historyData);

        // Calculate total credits and usage statistics
        const total = historyData.reduce(
          (sum, item) => sum + (item.credits || 0),
          0
        );
        setTotalCoins(total);

        const stats = {
          selfModel: historyData
            .filter((item) => item.type === "self_model")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          poster: historyData
            .filter((item) => item.type === "poster")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          youtube: historyData
            .filter((item) => item.type === "youtube")
            .reduce((sum, item) => sum + (item.credits || 0), 0),
          copywriting: historyData
            .filter((item) => ["caption", "blog_headings"].includes(item.type))
            .reduce((sum, item) => sum + (item.credits || 0), 0),
        };
        setUsageStats(stats);
      } catch (error) {
        console.error("Error fetching usage history:", error);
        // Handle error state if needed
      } finally {
        setLoading(false);
      }
    };

    fetchUsageHistory();
  }, [pagination.currentPage, pagination.limit, filterType]);

  const handleSearch = (e) => {
    setSearchTerm(e.target.value);
  };

  const handleFilterChange = (value) => {
    setFilterType(value);
  };

  const handleDateSelect = (range) => {
    setDateRange(range);
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return format(date, "MMM d, yyyy");
  };

  const exportCSV = () => {
    const headers = [
      "Type",
      "Content",
      "Credits",
      "Date",
      "Generated By",
      "Status",
    ];
    const csvData = usageData.map((item) => [
      item.type,
      item.content?.text || "",
      item.credits || 0,
      formatDate(item.createdAt),
      item.generatedBy || "",
      item.status,
    ]);

    const csvContent = [
      headers.join(","),
      ...csvData.map((row) => row.join(",")),
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", "usage_history.csv");
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  // console.log(usageData);

  return (
    <div className="space-y-6 max-w-7xl mx-auto px-4">
      {/* Usage Statistics Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Total Coins Used</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{totalCoins}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Self Model</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.selfModel}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.selfModel / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Poster Design</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.poster}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.poster / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">YouTube</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.youtube}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.youtube / totalCoins) * 100)}% of total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg">Copywriting</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{usageStats.copywriting}</div>
            <p className="text-xs text-muted-foreground">
              {Math.round((usageStats.copywriting / totalCoins) * 100)}% of
              total
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Search and Filter */}
      <div className="flex flex-col sm:flex-row justify-end gap-4">
        <div className="flex gap-2">
          <Select value={filterType} onValueChange={handleFilterChange}>
            <SelectTrigger className="text-nowrap">
              <SelectValue placeholder="Filter by type" />
            </SelectTrigger>
            <SelectContent className="bg-white">
              {selectOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select
            value={pagination.limit.toString()}
            onValueChange={(value) => {
              setPagination({
                ...pagination,
                limit: parseInt(value),
                currentPage: 1,
              });
            }}
          >
            <SelectTrigger className="text-nowrap">
              <SelectValue placeholder="10 per page" />
            </SelectTrigger>
            <SelectContent className="bg-white">
              <SelectItem value="25">25 per page</SelectItem>
              <SelectItem value="50">50 per page</SelectItem>
              <SelectItem value="100">100 per page</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="outline" onClick={exportCSV}>
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>
        </div>
      </div>

      {/* Usage History Table */}
      {loading ? (
        <LineLoading />
      ) : usageData.length > 0 ? (
        <Card>
          <CardContent className="p-4">
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-3 px-4">Type</th>
                    <th className="text-left py-3 px-4 hidden md:table-cell">
                      Content
                    </th>
                    <th className="text-left py-3 px-4">Credits</th>
                    <th className="text-left py-3 px-4">Date</th>
                    <th className="text-left py-3 px-4 text-nowrap">
                      Generated By
                    </th>
                    <th className="text-right py-3 px-4">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {usageData.map((item) => (
                    <tr key={item._id} className="border-b">
                      <td className="py-3 px-4">
                        <span
                          className={`inline-block text-center capitalize px-2 py-1 rounded-full text-xs ${getTaskTypeClass(
                            item.type
                          )}`}
                        >
                          {item.type.split("_").join(" ")}
                        </span>
                      </td>
                      <td className="py-3 px-4 hidden md:table-cell max-w-[300px] truncate">
                        <Link
                          href={`/${item.type}?${item._id}`}
                          className="hover:text-green-300"
                        >
                          {item.content?.text || ""}{" "}
                          {item.content.image ? (
                            <img
                              src={item.content.image}
                              className="max-w-14"
                            />
                          ) : (
                            ""
                          )}
                        </Link>
                      </td>
                      <td className="py-3 px-4 font-medium">
                        {item.credits || 0}
                      </td>
                      <td className="py-3 px-4">
                        {formatDate(item.createdAt)}
                      </td>
                      <td className="py-3 px-4">
                        {item.generatedBy.fullName || ""}
                      </td>
                      <td className="py-3 px-4 text-right">
                        <span
                          className={`inline-block px-2 py-1 rounded-full text-xs capitalize ${
                            item.status === "completed"
                              ? "bg-green-700"
                              : "bg-red-700"
                          }`}
                        >
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
          {/* Pagination Controls */}
          <div className="flex items-center justify-between border-t border-gray-700 px-4 py-3">
            <div className="flex items-center">
              <p className="text-sm text-gray-300">
                Showing <span className="font-medium">{usageData.length}</span>{" "}
                of <span className="font-medium">{pagination.totalItems}</span>{" "}
                history records
              </p>
            </div>
            <div className="flex items-center space-x-2">
              <div className="flex items-center space-x-1">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    if (pagination.currentPage > 1) {
                      setPagination({
                        ...pagination,
                        currentPage: pagination.currentPage - 1,
                      });
                    }
                  }}
                  disabled={pagination.currentPage === 1}
                >
                  Previous
                </Button>
                <div className="flex items-center">
                  {Array.from(
                    { length: Math.min(5, pagination.totalPages) },
                    (_, i) => {
                      // Show pages around current page
                      let pageToShow;
                      if (pagination.totalPages <= 5) {
                        pageToShow = i + 1;
                      } else {
                        const start = Math.max(1, pagination.currentPage - 2);
                        const end = Math.min(pagination.totalPages, start + 4);
                        pageToShow = start + i;
                        if (pageToShow > end) return null;
                      }

                      return (
                        <Button
                          key={pageToShow}
                          variant={
                            pagination.currentPage === pageToShow
                              ? "default"
                              : "outline"
                          }
                          size="sm"
                          className="w-9"
                          onClick={() => {
                            setPagination({
                              ...pagination,
                              currentPage: pageToShow,
                            });
                          }}
                        >
                          {pageToShow}
                        </Button>
                      );
                    }
                  )}
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    if (pagination.currentPage < pagination.totalPages) {
                      setPagination({
                        ...pagination,
                        currentPage: pagination.currentPage + 1,
                      });
                    }
                  }}
                  disabled={pagination.currentPage === pagination.totalPages}
                >
                  Next
                </Button>
              </div>
            </div>
          </div>
        </Card>
      ) : (
        <div className="text-center py-12">
          <Filter className="h-16 w-16 text-gray-400 mx-auto mb-4" />
          <h3 className="text-xl font-semibold text-white mb-2">
            No usage history found
          </h3>
          <p className="text-white/70">
            {searchTerm ||
            filterType !== "all" ||
            dateRange.from ||
            dateRange.to
              ? "Try adjusting your search or filters"
              : "No usage history available yet."}
          </p>
        </div>
      )}
    </div>
  );
};

// Helper function for task type styling
const getTaskTypeClass = (type) => {
  switch (type) {
    case "self_model":
      return "bg-blue-100 text-blue-800";
    case "poster":
      return "bg-purple-100 text-purple-800";
    case "youtube":
      return "bg-red-100 text-red-800";
    case "caption":
      return "bg-green-100 text-green-800";
    case "blog_headings":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

export default UsageHistory;
